global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'java-old'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'java'
    static_configs:
      - targets: ['host.docker.internal:8082']
