{
 "title": "CPU load average",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{instance=\"cadvisor:8080\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_cpu_system_seconds_total{instance=\"cadvisor:8080\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_cpu_user_seconds_total{instance=\"cadvisor:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_cpu_load_average_10s{instance=\"cadvisor:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expression": "$A/1000000", "type": "math" }
   ]
  }
 ]
}