{
 "title": "Demo: Java",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(java_request_duration_seconds_bucket[1m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(java_request_duration_seconds_bucket[1m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Java in progress threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "java_inprogress_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(java_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM used memory (non heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\"} / 1000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_init_bytes{area=\"nonheap\"} / 1000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM used memory (heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"} / 1000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_init_bytes{area=\"heap\"} / 1000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "__auto" },
    { "expr": "jvm_threads_daemon", "legendFormat": "__auto" },
    { "expr": "jvm_threads_deadlocked", "legendFormat": "__auto" }
   ]
  }
 ]
}