{
 "title": "System",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "go GC pause (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expression": "$A * 1000", "type": "math" }
   ]
  },
  {
   "title": "CPU load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_cpu_load_average_10s{instance=\"cadvisor:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage (user)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(id) (container_cpu_user_seconds_total{instance=\"cadvisor:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(id) (container_memory_usage_bytes) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}